CREATE TABLE IF NOT EXISTS document
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date        TIMESTAMP NOT NULL,
    patient_id  BIGINT NOT NULL,
    hospital_id BIGINT NOT NULL,
    doctor_id   BIGINT NOT NULL,
    room        VARCHAR(255) NOT NULL,
    data        TEXT
);